CREATE TABLE Roles (
    Id INT PRIMARY KEY IDENTITY(1,1),
    Name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE Users (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    Email VARCHAR(255) UNIQUE,
	Phone VARCHAR(255) UNIQUE,
    UserName VARCHAR(100),
    PasswordHash VARCHAR(512) NOT NULL,
    IsEmailVerified BIT DEFAULT 0,
    IsPhoneVerified BIT DEFAULT 0,
    CreatedAt DATETIME NOT NULL DEFAULT GETDATE(),
    UpdatedAt DATETIME NOT NULL DEFAULT GETDATE(),
    IsActive BIT NOT NULL DEFAULT 1,
    RoleId INT NOT NULL DEFAULT 'User',

    CONSTRAINT FK_Users_Roles FOREIGN KEY (RoleId) REFERENCES Roles(Id)
);

CREATE TABLE UserLogins (
    LoginId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    UserId UNIQUEIDENTIFIER NOT NULL,
    LoginTime DATETIME NOT NULL,
    IpAddress VARCHAR(45) NULL,
    DeviceInfo VARCHAR(255) NULL,

    CONSTRAINT FK_Logins_Users FOREIGN KEY (UserId) REFERENCES Users(Id) ON DELETE CASCADE
);

CREATE TABLE UserVerifications (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    UserId UNIQUEIDENTIFIER NOT NULL,
    ContactType VARCHAR(10) NOT NULL CHECK (ContactType IN ('Email', 'Phone')),
    ContactValue VARCHAR(255) NOT NULL,
    VerificationCode VARCHAR(100) NOT NULL,
    CodeType VARCHAR(20) NOT NULL CHECK (CodeType IN ('Token', 'OTP')),
    Purpose VARCHAR(30) NOT NULL CHECK (Purpose IN ('AccountVerification', 'PasswordReset')),
    ExpiresAt DATETIME NOT NULL,
    IsUsed BIT DEFAULT 0,
    CreatedAt DATETIME DEFAULT GETDATE(),

    CONSTRAINT FK_UserVerifications_Users FOREIGN KEY (UserId) REFERENCES Users(Id) 
);

CREATE TABLE PasswordResetTokens (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    UserId UNIQUEIDENTIFIER NOT NULL,
    Token VARCHAR(512) NOT NULL,
    ExpiresAt DATETIME NOT NULL,
    IsUsed BIT DEFAULT 0,
    CreatedAt DATETIME DEFAULT GETDATE(),
    CONSTRAINT FK_PasswordResetTokens_Users FOREIGN KEY (UserId)  REFERENCES Users(Id) 
);

CREATE TABLE RefreshTokens (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    UserId UNIQUEIDENTIFIER NOT NULL,
    Token VARCHAR(512) NOT NULL,
    ExpiresAt DATETIME NOT NULL,
    IsRevoked BIT DEFAULT 0,
    CreatedAt DATETIME DEFAULT GETDATE(),
    CONSTRAINT FK_RefreshTokens_Users FOREIGN KEY (UserId) REFERENCES Users(Id)
);


