-- Login Table
CREATE TABLE Login (
    LoginId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    UserId UNIQUEIDENTIFIER NOT NULL,
    LoginTime DATETIME NOT NULL DEFAULT GETDATE(),
    IpAddress VARCHAR(100),
    DeviceInfo NVARCHAR(MAX),
    FOREIGN KEY (UserId) REFERENCES Users(Id) ON DELETE CASCADE
);
